<a href="https://colab.research.google.com/github/rawanhussein77/functions/blob/main/Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas  as pd
import plotly.express as px

df = pd.read_csv(r"/country_wise_latest (1).csv")
df.info()
data = pd.read_csv(r"/country_wise_latest (1).csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

In [ ]:
import pandas as pd
data = pd.read_csv("/country_wise_latest (1).csv")

In [ ]:
data.count()

Country/Region            187
Confirmed                 187
Deaths                    187
Recovered                 187
Active                    187
New cases                 187
New deaths                187
New recovered             187
Deaths / 100 Cases        187
Recovered / 100 Cases     187
Deaths / 100 Recovered    187
Confirmed last week       187
1 week change             187
1 week % increase         187
WHO Region                187
dtype: int64

In [ ]:
data.isnull().sum()

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64

In [ ]:
import dash
from dash import dcc, html
import pandas as pd
import plotly.graph_objects as go

data = pd.read_csv(r"/country_wise_latest (1).csv")


missing_values = data.isnull().astype(int)

fig = go.Figure(
    data=go.Heatmap(
        z=missing_values.values,
        x=missing_values.columns,
        y=[f"Row {i}" for i in range(len(missing_values))],
        colorscale="Blues",
        showscale=True
    )
)


fig.update_layout(
    title="Heatmap of Missing Values",
    xaxis_title="Columns",
    yaxis_title="Rows",
    template="plotly"
)


app = dash.Dash(__name__)


app.layout = html.Div([
    html.H1("COVID-19 Missing Values Heatmap", style={"textAlign": "center"}),


    dcc.Graph(figure=fig, id="heatmap-graph")
])

if __name__ == "__main__":
    app.run_server(debug=True)

In [ ]:
data.head()

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [69]:
data.groupby('Country/Region')['Recovered'].sum()

Country/Region
Afghanistan           25198
Albania                2745
Algeria               18837
Andorra                 803
Angola                  242
                      ...
West Bank and Gaza     3752
Western Sahara            8
Yemen                   833
Zambia                 2815
Zimbabwe                542
Name: Recovered, Length: 187, dtype: int64

In [70]:
data.groupby('Country/Region')['Deaths'].sum().sort_values(ascending=False)

Country/Region
US                148011
Brazil             87618
United Kingdom     45844
Mexico             44022
Italy              35112
                   ...
Laos                   0
Greenland              0
Cambodia               0
Grenada                0
Mongolia               0
Name: Deaths, Length: 187, dtype: int64

In [ ]:
data[~(data.Deaths < 10)]

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,Venezuela,15988,146,9959,5883,525,4,213,0.91,62.29,1.47,12334,3654,29.63,Americas
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [ ]:
data.groupby('Country/Region').Active.sum().sort_values(ascending=False)

Country/Region
US                2816444
Brazil             508116
India              495499
United Kingdom     254427
Russia             201097
                   ...
Holy See                0
San Marino              0
Brunei                  0
Dominica                0
Grenada                 0
Name: Active, Length: 187, dtype: int64

In [71]:
data[data['Country/Region']=='Russia']

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe

In [ ]:
import plotly.express as px
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import pandas as pd


countries = ['Italy', 'Yemen', 'Albania', 'Andorra', 'Zimbabwe', 'Algeria']
filtered_data = data[data['Country/Region'].isin(countries)]

variables = ['Confirmed', 'Deaths', 'Recovered', 'Active']

app = dash.Dash(__name__)


app.layout = html.Div([
    html.H1("COVID-19 Data Distribution"),


    dcc.Dropdown(
        id='country-dropdown',
        options=[{'label': country, 'value': country} for country in countries],
        value=countries,
        multi=True,
        style={'width': '50%'}
    ),


    dcc.Graph(id='confirmed-graph'),
    dcc.Graph(id='deaths-graph'),
    dcc.Graph(id='recovered-graph'),
    dcc.Graph(id='active-graph')
])

@app.callback(
    [Output('confirmed-graph', 'figure'),
     Output('deaths-graph', 'figure'),
     Output('recovered-graph', 'figure'),
     Output('active-graph', 'figure')],
    [Input('country-dropdown', 'value')]
)
def update_graphs(selected_countries):

    filtered_data = data[data['Country/Region'].isin(selected_countries)]


    fig_confirmed = px.histogram(filtered_data, x='Confirmed', color='Country/Region', nbins=10, title='Distribution of Confirmed Cases')
    fig_deaths = px.histogram(filtered_data, x='Deaths', color='Country/Region', nbins=10, title='Distribution of Deaths')
    fig_recovered = px.histogram(filtered_data, x='Recovered', color='Country/Region', nbins=10, title='Distribution of Recovered Cases')
    fig_active = px.histogram(filtered_data, x='Active', color='Country/Region', nbins=10, title='Distribution of Active Cases')

    return fig_confirmed, fig_deaths, fig_recovered, fig_active

if __name__ == '__main__':
    app.run_server(debug=True)

In [59]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd

import plotly.graph_objects as go

app = dash.Dash(__name__)

numerical_data = data.select_dtypes(include=['number'])
numerical_data = numerical_data.drop(columns=['WHO Region'], errors='ignore')

corr_matrix = numerical_data.corr()

fig = go.Figure(data=go.Heatmap(
    z=corr_matrix.values,
    x=corr_matrix.columns,
    y=corr_matrix.columns,
    colorscale=[[0, 'blue'], [1, 'red']],
    zmin=-1, zmax=1,
    colorbar=dict(title='Correlation Coefficient')
))


app.layout = html.Div([
    html.H1('Correlation Matrix of COVID-19 Data', style={'text-align': 'center'}),
    dcc.Graph(
        id='correlation-heatmap',
        figure=fig
    )
])


if __name__ == '__main__':
    app.run_server(debug=True)

In [60]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
from dash.dependencies import Input, Output


country_deaths = data.groupby('Country/Region')['Deaths'].sum().reset_index()
country_deaths = country_deaths.sort_values(by=['Deaths'], ascending=False)
top_10_countries = country_deaths.head(10)

fig = px.bar(top_10_countries, x='Country/Region', y='Deaths',
             title='Total Deaths by Country (Top 10)',
             labels={'Deaths': 'Total Deaths', 'Country/Region': 'Country/Region'})

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("COVID-19 Deaths Dashboard", style={'text-align': 'center'}),
    dcc.Graph(id='death-bar-chart', figure=fig),
])

if __name__ == '__main__':
    app.run_server(debug=True)

In [61]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import plotly.express as px
import pandas as pd
from dash.dependencies import Input, Output

country_recoveries = data.groupby('Country/Region')['Recovered'].sum().reset_index()


country_recoveries = country_recoveries.sort_values(by=['Recovered'], ascending=False)
top_10_countries = country_recoveries.head(10)

fig = px.bar(top_10_countries, x='Country/Region', y='Recovered',
             title='Total Recoveries by Country (Top 10)',
             labels={'Recovered': 'Total Recoveries', 'Country/Region': 'Country/Region'})


app = dash.Dash(__name__)


app.layout = html.Div([
    html.H1("COVID-19 Recoveries Dashboard", style={'text-align': 'center'}),


    dcc.Dropdown(
        id='num-countries',
        options=[{'label': str(i), 'value': i} for i in range(1, 21)],
        value=10,
        style={'width': '40%', 'margin': 'auto'}
    ),


    dcc.Graph(id='recovery-bar-chart', figure=fig),
])

@app.callback(
    Output('recovery-bar-chart', 'figure'),
    [Input('num-countries', 'value')]
)
def update_graph(num_countries):

    top_countries = country_recoveries.head(num_countries)


    fig = px.bar(top_countries, x='Country/Region', y='Recovered',
                 title=f'Total Recoveries by Country (Top {num_countries})',
                 labels={'Recovered': 'Total Recoveries', 'Country/Region': 'Country/Region'})

    return fig


if __name__ == '__main__':
    app.run_server(debug=True)

In [63]:
import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd


data = pd.read_csv(r"/country_wise_latest (1).csv")


fig = px.box(data, x='WHO Region', y='Deaths',
             title='Distribution of Deaths by WHO Region',
             labels={'Deaths': 'Deaths', 'WHO Region': 'WHO Region'})


app = dash.Dash(__name__)


app.layout = html.Div(children=[
    html.H1('Interactive Dashboard: Distribution of Deaths by WHO Region'),
    dcc.Graph(figure=fig),
])


if __name__ == '__main__':
    app.run_server(debug=True)

In [64]:
import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd
data = pd.read_csv(r"/country_wise_latest (1).csv")
region_recoveries = data.groupby('WHO Region')['Recovered'].sum().reset_index()


fig = px.bar(region_recoveries,
             x='WHO Region',
             y='Recovered',
             title='Total Recoveries by WHO Region',
             labels={'Recovered': 'Total Recoveries', 'WHO Region': 'WHO Region'})


app = dash.Dash(__name__)


app.layout = html.Div(children=[
    html.H1('Interactive Dashboard: Total Recoveries by WHO Region'),
    dcc.Graph(figure=fig),
])

if __name__ == '__main__':
    app.run_server(debug=True)

In [67]:
import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd
data = pd.read_csv(r"/country_wise_latest (1).csv")

fig = px.histogram(data,
                   x='Confirmed',
                   nbins=50,
                   title='Distribution of Confirmed Cases',
                   labels={'Confirmed': 'Confirmed Cases'},
                   marginal='box',
                   opacity=0.75)


app = dash.Dash(__name__)


app.layout = html.Div(children=[
    html.H1(' Distribution of Confirmed Cases'),
    dcc.Graph(figure=fig),
])


if __name__ == '__main__':
    app.run_server(debug=True)